application: tagtooadex2
version: 1
runtime: python27
api_version: 1
threadsafe: true



libraries:
- name: jinja2
  version: latest
- name: django
  version: 1.5
- name: ssl
  version: latest
- name: lxml
  version: latest
- name: MySQLdb
  version: latest

builtins:
- django_wsgi: on
- deferred: on
- remote_api: on
- appstats: on
- admin_redirect: on


handlers:

- url: /.*
  #script: index.app
  script: example.wsgi.application


env_variables:
  DJANGO_SETTINGS_MODULE: 'example.settings'

skip_files:
- .*\.DS_Store
- \.git/*
- local_settings.pyc?$
- .*\.pyc
- .*\.rb
- .*\.sass
- .*\.scss
- \.svn/*
- \.svn\-base
- google/


automatic_scaling:
  max_idle_instances: 1
  max_pending_latency: 5000ms
  #max_concurrent_requests: 10
